## Frontend deployment values

frontend:
  enabled: true

  replicaCount: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  image:
    repository: rajeshkosta/application-code-frontend
    pullPolicy: Always
    tag: v1

  service:
    type: ClusterIP
    port: 80


  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi


  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5

  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 10

  nodeSelector:
    role: frontend

  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - frontend

## Backend Deployment values

backend:
  enabled: true

  replicaCount: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  image:
    repository: rajeshkosta/application-code-backend
    pullPolicy: Always
    tag: v1

  service:
    type: ClusterIP
    port: 3500

  env:
    NODE_ENV: production
    PORT: "3500"
    MONGODB_URI: mongodb://root:MyStrongPass123@mongo-mongodb.db.svc.cluster.local:27017/wanderlust?authSource=admin
    REDIS_URL: redis://:MyStrongPass123@redis-master.db.svc.cluster.local:6379
#    MONGODB_URI: mongodb://root:ibxYgykSyA@mongo-mongodb:27017/wanderlust?authSource=admin
#    REDIS_URL: redis://redis-master:6379

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  readinessProbe:
    httpGet:
      path: /ok
      port: 3500
    initialDelaySeconds: 10
    periodSeconds: 5

  livenessProbe:
    httpGet:
      path: /ok
      port: 3500
    initialDelaySeconds: 30
    periodSeconds: 10

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  nodeSelector:
    role: backend

  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "backend"
    effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - backend

## Ingress Deployment values

ingress:
  enabled: true

  className: nginx

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
#    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"

  host: wanderlust.local
